apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: money-movement-management
  description: Money Movement Management
spec:
  type: business-unit 
  profile:
    displayName: Money Movement Management
  parent: rusbe
  children: []
