openapi: 3.0.1
info:
  title: CSF.AccountManagement.Saldo.Api
  description: >-
    <br>Repositório: <a href='LINK'
    target='_blank'>CSF.AccountManagement.Saldo.Api</a>
  version: v1
servers:
  - url: >-
      https://api-accountmanagement-saldo-csf-hml-accountmanagement-cc.gkehml.gcp.wcorp.carrefour.com
paths:
  /v1/accounts/{accountId}/balance:
    get:
      tags:
        - Balance
      operationId: Balance
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBalanceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '503':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearer: []
  /api/test-log-level:
    get:
      tags:
        - Log
      parameters:
        - name: data
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /api/change-level:
    get:
      tags:
        - Log
      parameters:
        - name: logLevel
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
      additionalProperties: false
    GetBalanceResponse:
      type: object
      properties:
        balance:
          type: number
          format: double
        unavailableBalance:
          type: number
          format: double
        lastUpdatedAt:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    bearer:
      type: http
      description: "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter your token in the text input below.\r\n\r\nExample: \"12345abcdef\""
      scheme: bearer
      bearerFormat: JWT